# Generated by Django 5.0.6 on 2024-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=4000, null=True, upload_to='post_image/', verbose_name='Post Image Content', width_field=4000),
        ),
    ]
