# Generated by Django 5.0.6 on 2024-05-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_kicked_until_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('kick_user', 'Can kick users')]},
        ),
    ]
